name: Test and Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  test:
    name: Test Python Lambda Function
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 moto pytest pytest-cov
    
    - name: Run tests
      working-directory: ./backend/lambda
      run: |
        pytest test_app.py --cov=app --cov-report=term-missing
  
  deploy:
    name: Deploy SAM Application
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up AWS SAM
      uses: aws-actions/setup-sam@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: SAM build
      working-directory: ./backend
      run: sam build
    
    - name: SAM deploy
      working-directory: ./backend
      run: |
        sam deploy \
          --stack-name visitor-counter-stack \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides Environment=prod
    
    - name: Get API Gateway URL
      id: get-api-url
      working-directory: ./backend
      run: |
        API_URL=$(aws cloudformation describe-stacks \
          --stack-name visitor-counter-stack \
          --query "Stacks[0].Outputs[?OutputKey=='VisitorCounterApiEndpoint'].OutputValue" \
          --output text)
        echo "API_URL=$API_URL" >> $GITHUB_ENV
    
    - name: Output API URL
      run: |
        echo "✅ API Gateway URL: ${{ env.API_URL }}"
        echo "Remember to update your frontend JavaScript to use this URL for the visitor counter API calls."